import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
<<<<<<< HEAD
import Head from "next/head";
=======
>>>>>>> 82e94024455ece946db7e44dba3bd0f74ee6b49c

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
<<<<<<< HEAD
  title: {
    default: "INAU - Institut National d'Aménagement et d'Urbanisme",
    template: "INAU - %s",
  },
=======
  title: "Create Next App",
>>>>>>> 82e94024455ece946db7e44dba3bd0f74ee6b49c
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <Head>
        {/* Fallback title for robustness, but dynamic title is handled by Next.js metadata */}
        <link rel="icon" href="/images/logoinau.png" type="image/png" />
      </Head>
=======
>>>>>>> 82e94024455ece946db7e44dba3bd0f74ee6b49c
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Header />
        <div className="pt-[96px] bg-white min-h-screen">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
